### ISSUE TITLE
Additional Upcoming Events for August Issue

### ISSUE THREAD

**Issue by nottrunner** [xaur/decred-news#101]
Sept 20 [A Framework for Blockchain Governance Meetup](https://www.eventbrite.com/e/a-framework-for-blockchain-governance-tickets-70134180221) Washington DC. Along with Thomas Cox, the Chief Governance Officer of [StrongBlock](https://strongblock.io/), Akin Sawyerr will be speaking on and taking questions on a Blockchain Governance Framework developed the Wharton Crypto Governance roundtable group of which he is a member. 

Oct 29 - 31 [World Crypto Conference](https://worldcryptocon.com/) Las Vegas, Nevada. Akin Sawyerr will be speaking on a panel on "Governance Practices" and will have an opportunity to highlight the Decred governance model and process.

**Comment by xaur** [comment]
Added, thanks for the ready text!

Change: f6396b396d83e74c6d7606a22443655437a7ab44

I used the Matrix display name `@Akin`. Let me know if you would like something else.

**Comment by nottrunner** [comment]
My matrix name is actually @akinsawyerr

·······················································
AKIN SAWYERR /  Strategy + Governance /  DECRED
························································
email akin@feleman.com   /  web decred.org

**Comment by xaur** [comment]
Ok used that, thanks!
