### ISSUE TITLE
DJ September 2019

### ISSUE THREAD

**Issue by xaur** [xaur/decred-news#104]
Link to the draft: https://github.com/xaur/decred-news/blob/draft09/journal/201909.md

**Dependencies**: Send notice in advance so people can plan their work.

- [x] Title image via an [issue in dcrdesign](https://github.com/decred/dcrdesign/issues) (notify by: 20th, ready by: 3rd)
  * GitHub version must be 768x384 px
  * ask for image title and description (saender)
- [x] first time contributors (degeri or s_ben)
- [x] dev activity stats (degeri or s_ben)
- [x] Ditto update (cryptoleslie or liz_bagot, notify by: 28th, ready by: 3rd)
- [x] Outreach update (Dustorf, notify by: 28th, ready by: 3rd)

**End of month snapshots**: Snapshot data that is hard to obtain later.

- [x] snapshot social media stats
  * Politeia, Matrix, Discord, Slack, Telegram, Twitter, Reddit, YouTube, Facebook, LinkedIn, GitHub dcrd, Instagram
  * (opt) non-English platforms: Telegram (es pt zh it ru), Twitter (es), Instagram
- [x] staking
  * 30-day average ticket price (https://dcrstats.com)
- [x] nodes
  * node count, versions, etc (ask chappjc or #dev or dcr.farm)

**Release**

- [x] Extract more dev updates from GitHub repos
- [x] Complete Development (by: 2nd)
- [x] Complete People (by: 2nd)
- [x] PO review Development and People
- [x] Ask in #dev to review Development and People
- [x] Complete Events
- [x] (opt) Ask #event_planning to review Events
- [x] Complete Outreach
- [x] Complete Media
- [x] (opt) Ask #marketing to review Outreach+Events+Media
- [x] Complete Governance
- [x] Complete Network
- [x] Complete Mining, Integrations, Adoption
- [x] (opt) Find interesting Reddit and Twitter threads
- [x] Complete Community Discussions
- [x] Complete Markets
- [x] Complete Relevant External
- [x] (opt) Ask quoted people to review their texts
- [x] Complete Intro
- [x] Pre-review: check spelling, grammar, test that links work
- [x] PO review of all sections
- [x] Add [title image](https://github.com/xaur/decred-news/blob/docs/guidelines.md#title-image)
- [x] Ask #writers_room to review (by: 3rd)
- [x] Incorporate all feedback
- [x] Resolve all [TODOs](https://github.com/xaur/decred-news/blob/docs/guidelines.md#todos)
- [x] Carefully check that all people who contributed or gave feedback are in [credits](https://github.com/xaur/decred-news/blob/docs/guidelines.md#how-to-give-credit)
- [x] [Lint](https://github.com/xaur/decred-news/blob/docs/guidelines.md#linting)
- [x] Remove `{DRAFT}` from title
- [x] Pre-release review
- [x] Publish on GitHub with a single commit to `gh-pages`
- [x] Publish on Medium (richardred or Haon)
- [x] (opt) Verify Medium version, check for formatting issues
- [x] Choose the best link to disseminate: Medium vs GitHub Pages vs decredcommunity, etc
- [x] Submit best link to r/decred
- [x] Tweet best link via decredproject. Don't forget to add title image. (by: 6th)
- [x] If bugs are found in the published version quickly after the release, add commits to the draft branch and amend the commit on `gh-pages`
- [x] Fast-forward `master` to `gh-pages`
- [x] If changes are necessary after the release (>1 h), add extra commits to both `master` and `gh-pages`.
- [x] [Update index](https://github.com/xaur/decred-news/blob/docs/guidelines.md#updating-index)
- [x] Create Git tag from the draft branch, e.g. `archive/draft1901`
- [x] Delete the draft branch
- [x] (opt) Update `journal-template.md` in `docs` branch
- [x] (opt) Update this release checklist template in the `docs` branch

**Comment by nottrunner** [comment]
Sep 20 - A Framework for Blockchain Governance

Participated in a governance presentation with Thomas Cox of [StrongBlock](https://strongblock.io/) at [Blockshop](https://www.blockshopdc.com/) in Washington DC. Engaged in a Q&A session on Blockchain Governance and perspectives on Decred's governance process.

**Comment by nottrunner** [comment]
Oct 29-31 - World Crypto Conference - Las Vegas, USA. 

@AkinSawyerr will be speaking on a panel on "Governance Practices" and will also give a presentation titled: "Governing the Crypto Commons". The presentation will highlight Decred's governance process in contrast with other efforts across the public blockchain space.

**Comment by xaur** [comment]
Added, thank you @nottrunner

**Comment by Emilio-Mann** [comment]
Hey @xaur  what do you think about putting the official campus party goiania link instead of that tweet? https://brasil.campus-party.org/campus-party-goias/

**Comment by xaur** [comment]
@Emilio-Mann good idea. Changed to the official link and also used your imgur album link for photos. Thanks for that one btw.

**Comment by xaur** [comment]
To anyone not needing notifications from this routine release issue, hit Unsubscribe.

**Comment by xaur** [comment]
testing escape: `https://github.com/decred/dcrd/pull/1867`

**Comment by xaur** [comment]
### Governance

Turnout numbers are important, added them to proposal paragraphs and a note to mention them in the guidelines https://github.com/xaur/decred-news/commit/6cd09ac1

**Comment by xaur** [comment]
### Network

> Pool hashrate distribution as of Oct 2: UUPool 20.8%, Poolin 18.9%, F2Pool 18.8%, lab.antpool.com 5.8%, BTC.com 2.9%, Luxor 2.12%, Coinmine 0.10%, BeePool 0.10%, suprnova 0.03% and others 30.31%

Decimal places don't add much for two-digit numbers, and besides those numbers are very volatile https://github.com/xaur/decred-news/blob/docs/guidelines.md#typography

> Locked amount was 5.25-5.31 million DCR, which corresponded to 49.93-51.03% of the available supply.

Managed to squeeze out slightly different numbers from

https://charts.dcr.farm/d/000000003/proof-of-stake?orgId=1&from=1567209600000&to=1569974400000

and

https://explorer.dcrdata.org/charts?chart=stake-participation&zoom=jztk85t3-k198meqc&bin=block&axis=time

> Roughly 82.6% run dcrd v1.4.0, 9% are dcrwallet v1.4.0 and 8% are v1.5.0(pre) dev builds.

Always add the date of the data snapshot.

> On average for the month of september the DCR testnet LN shows 17 nodes, 40 channels and a total capacity of 227 DCR.

Got 35 channels via https://charts.dcr.farm/d/DHPdAO4Wz/lightning-network?orgId=1&from=1567296000000&to=1569888000000

All minor stuff though.
