### ISSUE TITLE
DJ November 2019

### ISSUE THREAD

**Issue by xaur** [xaur/decred-news#108]
**DRAFT**: https://github.com/xaur/decred-news/blob/draft11/journal/201911.md

**Dependencies**: Send notice in advance so people can plan their work.

- [x] Title image via an [issue in dcrdesign](https://github.com/decred/dcrdesign/issues) (notify by: 20th, ready by: 3rd)
  * GitHub version must be 768x384 px
  * ask for image title and description (saender)
- [x] first time contributors (degeri or s_ben)
- [x] dev activity stats (degeri or s_ben)
- [x] Ditto update (cryptoleslie or liz_bagot, notify by: 28th, ready by: 3rd)
- [x] Outreach update (Dustorf, notify by: 28th, ready by: 3rd)

**End of month snapshots**: Snapshot data that is hard to obtain later.

- [x] snapshot social media stats
  * Politeia, Matrix, Discord, Slack, Telegram, Twitter, Reddit, YouTube, Facebook, LinkedIn, GitHub dcrd, Instagram
  * (opt) non-English platforms: Telegram (es pt zh it ru), Twitter (es), Instagram
- [x] staking
  * 30-day average ticket price (https://dcrstats.com)
- [x] nodes
  * node count, versions, etc (ask chappjc or #dev or dcr.farm)

**Release**

- [x] Extract more dev updates from GitHub repos
- [x] Complete Development (by: 2nd)
- [x] Complete People (by: 2nd)
- [x] PO review Development and People
- [x] Ask in #dev to review Development and People
- [x] Complete Events
- [x] (opt) Ask #event_planning to review Events
- [x] Complete Outreach
- [x] Complete Media
- [x] (opt) Ask #marketing to review Outreach+Events+Media
- [x] Complete Governance
- [x] Complete Network
- [x] Complete Mining, Integrations, Adoption
- [x] (opt) Find interesting Reddit and Twitter threads
- [x] Complete Community Discussions
- [x] Complete Markets
- [x] Complete Relevant External
- [x] (opt) Ask quoted people to review their texts
- [x] Complete Intro
- [x] Pre-review: check spelling, grammar, test that links work
- [x] PO review of all sections
- [x] Add [title image](https://github.com/xaur/decred-news/blob/docs/guidelines.md#title-image)
- [x] Ask #writers_room to review (by: 3rd)
- [x] Incorporate all feedback
- [x] Resolve all [TODOs](https://github.com/xaur/decred-news/blob/docs/guidelines.md#todos)
- [x] Carefully check that all people who contributed or gave feedback are in [credits](https://github.com/xaur/decred-news/blob/docs/guidelines.md#how-to-give-credit)
- [x] [Lint](https://github.com/xaur/decred-news/blob/docs/guidelines.md#linting)
- [x] Remove `{DRAFT}` from title
- [x] Pre-release review
- [x] Publish on GitHub with a single commit to `gh-pages`
- [x] Publish on Medium (richardred or Haon)
- [x] (opt) Verify Medium version, check for formatting issues
- [x] Choose the best link to disseminate: Medium vs GitHub Pages vs decredcommunity, etc
- [x] Submit best link to r/decred
- [x] Tweet best link via decredproject. Don't forget to add title image. (by: 6th)
- [x] If bugs are found in the published version quickly after the release, add commits to the draft branch and amend the commit on `gh-pages`
- [x] Fast-forward `master` to `gh-pages`
- [x] If changes are necessary after the release (>1 h), add extra commits to both `master` and `gh-pages`.
- [x] [Update index](https://github.com/xaur/decred-news/blob/docs/guidelines.md#updating-index)
- [x] Create Git tag from the draft branch, e.g. `archive/draft1901`
- [ ] Delete the draft branch
- [x] (opt) Update `journal-template.md` in `docs` branch
- [x] (opt) Update this release checklist template in the `docs` branch

**Comment by xaur** [comment]
### Development

#### dcrd

> More robust and objective method introduced `https://github.com/decred/dcrd/pull/2000` for calculating total known work on the chain. This method is valid regardless of the order that blocks are received and process and does not rely on previously calculated checkpoints.

Reworded this to address the fact that no code was added to "calculate" total known work, rather a constant is hardcoded and updated with each release.

> Caching added `https://github.com/decred/dcrd/pull/2002` for least recently used key/value. {SB: what does this give us? not seeing any description on commit or PR…}

It adds the ability to insert and retrieve key-value pairs into/from the cache. Previously only inserting/retrieving values (without keys) was implemented. In other words, it adds "map-like" access pattern in addition to existing "set-like" one.

#### dcrwallet

Please use links to pull requests over links to commits.

> Method added to detect reused addresses `https://github.com/decred/dcrwallet/pull/1616` {SB: seems obvious this adds to privacy, but do we have examples to illustrate?}.

Not sure there will be a corresponding dcrctl command in v1.5, but the idea is that `auditreuse` returns you a list of your addresses that have been reused, and for each of those it lists outpoints using that address.

Not merged yet:

- New JSON RPC `https://github.com/decred/dcrwallet/pull/1611` for creating signatures {SB: what does this enable?}
-  multi: drop global activeNet usage: `https://github.com/decred/dcrwallet/pull/1610`

#### dcrstakepool

> Work continues to enable `https://github.com/decred/dcrstakepool/pull/571` voting outside of dcrwallet, allowing users to arbitrarily vote on tickets whose voting rights they have the private key for. {SB: potential applications of this ability?}

I think it allows the _VSP_ to vote, not users (it says "allows _us_") in the PR.

**Comment by xaur** [comment]
### Network

> Block 400k https://www.reddit.com/r/decred/comments/e0yvyb/block_400000/ {Is this significant ?}

Not too significant but is a fun round number to celebrate for beings favoring base-10 numbers.

**Comment by xaur** [comment]
Thanks all for another awesome release!

**Comment by s-ben** [comment]
Thx for the notes @xaur. On this one:

>dcrwallet
>Please use links to pull requests over links to commits.

I actually thought there was no work at first on dcrwallet just looking at the PRs. But then looked at the commits and saw all the activity. I think this is just due to jrick working on these solo (therefore not needing to do PRs). Also they seem to dislike documentation more than most. In this case, is linking to just commits OK?

**Comment by xaur** [comment]
@s-ben good point. You're right that some projects work in commits directly and skip PRs. If that is the case, or if the commit has more info than the PR, its ok to link to commits.
