### ISSUE TITLE
DJ December 2019

### ISSUE THREAD

**Issue by xaur** [xaur/decred-news#110]
**DRAFT**: https://github.com/xaur/decred-news/blob/draft12/journal/201912.md

**Dependencies**: Send notice in advance so people can plan their work.

- [x] Title image via an [issue in dcrdesign](https://github.com/decred/dcrdesign/issues) (notify by: 20th, ready by: 3rd)
  * GitHub version must be 768x384 px
  * ask for image title and description (saender)
- [x] first time contributors (degeri or s_ben)
- [x] dev activity stats (degeri or s_ben)
- [x] Ditto update (cryptoleslie or liz_bagot, notify by: 28th, ready by: 3rd)
- [x] Outreach update (Dustorf, notify by: 28th, ready by: 3rd)

**End of month snapshots**: Snapshot data that is hard to obtain later.

- [x] snapshot social media stats
  * Politeia, Matrix, Discord, Slack, Telegram, Twitter, Reddit, YouTube, Facebook, LinkedIn, GitHub dcrd, Instagram
  * (opt) non-English platforms: Telegram (es pt zh it ru), Twitter (es), Instagram
- [x] staking
  * 30-day average ticket price (https://dcrstats.com)
- [x] nodes
  * node count, versions, etc (ask chappjc or #dev or dcr.farm)

**Release**

- [x] Extract more dev updates from GitHub repos
- [x] Complete Development (by: 2nd)
- [x] Complete People (by: 2nd)
- [x] PO review Development and People
- [x] Ask in #dev to review Development and People
- [x] Complete Events
- [x] (opt) Ask #events to review Events
- [x] Complete Outreach
- [x] Complete Media
- [x] (opt) Ask #marketing to review Outreach+Events+Media
- [x] Complete Governance
- [x] Complete Network
- [x] Complete Mining, Integrations, Adoption
- [x] (opt) Find interesting Reddit and Twitter threads
- [x] Complete Community Discussions
- [x] Complete Markets
- [x] Complete Relevant External
- [x] (opt) Ask quoted people to review their texts
- [x] Complete Intro
- [x] Pre-review: check spelling, grammar, test that links work
- [x] PO review of all sections
- [x] Ask #writers to review (by: 3rd)
- [x] Incorporate all feedback
- [x] Resolve all [TODOs](https://github.com/xaur/decred-news/blob/docs/guidelines.md#todos)
- [x] Carefully check that all people who contributed or gave feedback are in [credits](https://github.com/xaur/decred-news/blob/docs/guidelines.md#how-to-give-credit)
- [x] [Lint](https://github.com/xaur/decred-news/blob/docs/guidelines.md#linting)
- [x] Add [title image](https://github.com/xaur/decred-news/blob/docs/guidelines.md#title-image)
- [x] Remove `{DRAFT}` from title
- [x] Pre-release review
- [x] Publish on GitHub with a single commit to `gh-pages`
- [x] Publish on Medium (richardred or Haon)
- [x] (opt) Verify Medium version, check for formatting issues
- [x] Choose the best link to disseminate: Medium vs GitHub Pages vs decredcommunity, etc
- [x] Submit best link to r/decred
- [x] Tweet best link via decredproject. Don't forget to add title image. (by: 6th)
- [x] If bugs are found in the published version quickly after the release, add commits to the draft branch and amend the commit on `gh-pages`
- [x] Fast-forward `master` to `gh-pages`
- [x] If changes are necessary after the release (>1 h), add extra commits to both `master` and `gh-pages`.
- [x] [Update index](https://github.com/xaur/decred-news/blob/docs/guidelines.md#updating-index)
- [x] Create Git tag from the draft branch, e.g. `archive/draft1901`
- [x] Delete the draft branch
- [x] (opt) Update `journal-template.md` in `docs` branch
- [x] (opt) Update this release checklist template in the `docs` branch
- [x] Start new cycle

**Comment by nottrunner** [comment]
Add to upcoming events:

- Jan 7 - [Digital Money forum at CES ](https://thedigitalmoneyforum.com/2020-agenda/) - Las Vegas, Nevada. @akinsawyerr will speak on a panel on the future of money

- Feb 4 - 6 - [Africa Tech Summit](https://www.africatechsummit/kigali/) - Kigali, Rwanda. @akinsawyerr will be a speaker in the Money & Blockchain Summit

**Comment by xaur** [comment]
Thanks @nottrunner, added the Feb event. I dropped the Jan 7 one because this DJ issue will be published afte Jan 7, making the event no longer an "upcoming" one. It will be included in Attended in January.

**Comment by xaur** [comment]
## Dev

### dcrd

> Advanced config option added `https://github.com/decred/dcrd/pull/2023` to enable prevention of unsynchronized mining on testnet.

As the description says, this is an advanced option for developers. I usually drop these, unless there is a good reason to include them.

> Deprecated TorLookupIP replaced `https://github.com/decred/dcrd/pull/2021` with TorLookupIPContext.

Small internal refactoring to add contexts (which allow cancellation of async processes). Dropping.

> main, dcrutil and hdkeychain modules updated `https://github.com/decred/dcrd/pull/2016` to use latest base58 module.

Minor internal dependency mgmt. Dropping.

> dcrutil support added `https://github.com/decred/dcrd/pull/2018` for calling the new auditreuse RPC.

We reported this feature in dcrwallet in 201911. Whoever needs this feature will need to build from source I think, until v1.6. Since this was reported earlier and is for advanced users, dropping.

> The blockchain module also modified to accept hash `https://github.com/decred/dcrd/pull/2022` in next work diff calcs. This is part of an overall effort to make the blockchain module more explicit and less reliant on the current state.

Good change but after some pondering I figured it is not very notable. Dropping.

> Key arrays replaced `https://github.com/decred/dcrd/pull/2015` with maps with string keys. Memory usage should be significantly reduced following this change for dcrd instances serving dcrwallet clients in RPC syncing mode with very many addresses.

This was not merged and was replaced with PR 2027, as noted in comments. It is worth to mention that it fixes a memory leak.

> multi: Address a bunch of lint issues: `https://github.com/decred/dcrd/pull/2028`

Nice but not notable, dropping.

> rpcwebsocket: Use nonblocking messages and ntfns: `https://github.com/decred/dcrd/pull/2026`

Looks like a small multitasking fix. Dropping.

> `https://github.com/decred/dcrd/pull/2008`

300-line refactoring with further decoupling. Adding.

> `https://github.com/decred/dcrd/pull/2011`

Clever hack of "tech goodness" category. Also touches consensus code. Adding.

### dcrwallet

Small or internal fixes and dependency mgmt, dropping:

- Dependencies updated for start of 1.6 development. `https://github.com/decred/dcrwallet/pull/1628`
- apply cleanAndExpandPath() on CSPPServer.ca option: `https://github.com/decred/dcrwallet/pull/1632`
- Update to recently-tagged JSON-RPC types package: `https://github.com/decred/dcrwallet/pull/1629`
- Remove pseudo-versions from main module: `https://github.com/decred/dcrwallet/pull/1627`
- Prepare walletseed/v1.0.3 with pgpwordlist 1.0.1: `https://github.com/decred/dcrwallet/pull/1626`
- Silence ticketbuyer insufficient balance errors: `https://github.com/decred/dcrwallet/pull/1624`

### Decrediton

Small or internal fixes, dropping:

- Protocol Buffers updated `https://github.com/decred/decrediton/pull/2349` to v3.4.0.

> DcrInput component now only requires a single prop ('amount'). Having to track both 'value' and 'amount' as consumer of DcrInput was cumbersome and led to some mistakes such as in the ticket buyer input that specifies the balance to maintain.

Internal refactoring, dropping.

A bunch of individual bugs grouped in "bug fixes".

### dcrstakepool

Too minor items this time, dropping the section.

### dcrlnd

Dropping already mentioned:

- github: add docker build job: `https://github.com/decred/dcrlnd/pull/67`

Dropping items that have no work in December or are not merged:

- Verify chainntfs in case of disapproved blocks: `https://github.com/decred/dcrlnd/issues/69`
- Network command line switches for `dcrlnd` and `dcrlncli`: `https://github.com/decred/dcrlnd/pull/72`

### dcrandroid

Group in "bug fixes", dropping:

- multi: verify dialog instance existence before creating a new instance: `https://github.com/decred/dcrandroid/pull/417`
- text fields disabled `https://github.com/decred/dcrandroid/pull/419` when processing

**Comment by xaur** [comment]
## Network

I [adjusted](https://github.com/xaur/decred-news/commit/c13c028f3478794cae022e6d7579d21a993703cd) the numbers a bit. On dcrdata I used higher resolution data by changing Bin from Day to Blocks and zooming in. On charts.dcr.farm I used time range of 2019-12-01 00:00 till 2020-01-01 00:00 UTC. Note that it displays time in the time zone reported by the browser. To exclude ambiguity you can check the `from` and `to` params in the URL that have the Unix time.

**Comment by xaur** [comment]
Thanks all for another great release!
