### ISSUE TITLE
External - The Coming Bitcoin War

### ISSUE THREAD

**Issue by bochinchero** [xaur/decred-news#147]
Really well thought out piece of how the (upcoming) flood of institutional money will come with strings attached, as these players will want to have a seat at the table to influence the direction of Bitcoin development.

Released late September.

https://medium.com/@dustindreifuerst/the-coming-bitcoin-war-ff3e96db3aad

**Comment by xaur** [comment]
Pretty realistic scenario. I'm a bit undecided whether it's "relevant enough" and will revise it again closer to release, but for now I added it to the October [draft](https://github.com/xaur/decred-news/blob/draft10/journal/202010.md). Thanks for the link.

**Comment by xaur** [comment]
Released in [October 2020](https://xaur.github.io/decred-news/journal/202010.html). Thanks.
