### ISSUE TITLE
Content

### ISSUE THREAD

**Issue by xaur** [xaur/decred-news#41]
Map of existing and possible content to cover, with some items marked for possible automation.

Moved here: https://github.com/xaur/decred-news/blob/docs/content.md

**Comment by RichardRed0x** [comment]
Following on from [chat](https://matrix.to/#/!lbzTjhzNbIaDbuAxkS:decred.org/$15500201449029YpzjF:decred.org?via=decred.org&via=matrix.org) earlier:
I should be able to do some of the stats requested fairly easily, and in a way which can become largely automated.
Reddit: Count of posts and comments, summed post scores
Politeia: Total number of distinct pubkey voters/commenters, number of new props/comments/votes in the month

**Comment by RichardRed0x** [comment]
Following on from [chat](https://matrix.to/#/!lbzTjhzNbIaDbuAxkS:decred.org/$15500201449029YpzjF:decred.org?via=decred.org&via=matrix.org) earlier:
I should be able to do some of the stats requested fairly easily, and in a way which can become largely automated.
Reddit: Count of posts and comments, summed post scores
Politeia: Total number of distinct pubkey voters/commenters, number of new props/comments/votes in the month

**Comment by xaur** [comment]
Moved the document here for easier maintenance (with git and my local text editor): https://github.com/xaur/decred-news/blob/docs/content.md
