### ISSUE TITLE
Translation in Portuguese - Decred Journal - December 2018

### ISSUE THREAD

**Issue by MaiconJunge** [xaur/decred-news#57]
Add, please!
https://github.com/MaiconJunge/decred-news/blob/master/journal/201812PTBR.md
https://medium.com/@maiconjunge/jornal-decred-dezembro-de-2018-947c616b894f
Thank you!

**Comment by xaur** [comment]
Added Medium as primary translation for simple index: https://xaur.github.io/decred-news

And github to full index: https://xaur.github.io/decred-news/mirrors.html
