### ISSUE TITLE
People working on Decred Journal 2.0 

### ISSUE THREAD

**Issue by degeri** [xaur/decred-news#65]
The work is being divided by various people.

Area|Owners
---|---
Introduction|richardred|
Development|s_ben, richardred
People|degeri
Governance|richardred
Network|degeri
Mining|degeri
Integrations|degeri
Outreach|Dustorf
Events|Dustorf
Media|richardred
Community Discussions|richardred
Markets|degeri
Relevant External|richardred
Overall production|richardred, bee

kozel and guang have also offered support.

Anyone from the community can pitch in by joining the #decred\_journal Matrix room (currently you need to request invite in #writers\_room).

**Comment by xaur** [comment]
Closing since this is settled for now. Reopen if needed.
