### ISSUE TITLE
DC Event June 12

### ISSUE THREAD

**Issue by nottrunner** [xaur/decred-news#73]
The June 12 event is a bit more than a meetup.  Its a jointly sponsored event with the Dartmouth Entrepreneurial Network and TechSpaces. Could you replace the current text with:

Join [Decred](decred.org), [The Dartmouth Entrepreneurial Network of DC](dendc.org), and [Techspaces](https://www.techspace.com/coworking-space-near-washington-dc-virginia/) for an evening of conversations and an overview of Decred: A Decentralized Autonomous Entity. Tickets are free but limited, get yours here: [Meetup](https://www.meetup.com/Decred-Washington-DC-Meetup-Group/events/261144707/)

**Comment by xaur** [comment]
I'll need an event title or type in place of the "Meetup" because we follow a standard format. Used the following text:

> Jun 12 - Meetup - Washington DC, USA. Join Decred, The Dartmouth Entrepreneurial Network of DC, and TechSpace for an evening of conversations and an overview of Decred: A Decentralized Autonomous Entity. Tickets are free but limited, available at meetup.com. Organized by `@akinsawyerr`.

Please let me know if it needs further tweaks.

**Comment by nottrunner** [comment]
Looks good. Can we just say availbe here or meetup with a hyperlink to the page? http://bit.ly/DecredDENMeetup

**Comment by xaur** [comment]
Changed to "available here".

https://github.com/xaur/decred-news/blob/draft05/journal/201905.md

I try to use full canonical links because a) URL shorteners can track links, and b) meetu.ps links redirect to login page.

Closing, reopen if necessary.
