### ISSUE TITLE
San Francisco event on July 1st and 2nd 2019

### ISSUE THREAD

**Issue by nottrunner** [xaur/decred-news#74]
I'll be attending a governance round-table event on behalf of Decred.  Here are the details:

The Zicklin Center for Business Ethics Research at the Wharton School of the University of Pennsylvania is launching a new initiative on the governance of blockchain-related projects, platforms, and consortia. We are hosting an initial meeting at Wharton San Francisco for approximately 25 highly-esteemed experts, representing a wide variety of perspectives and backgrounds.

July 1-2, 2019
Wharton Roundtable on Cryptogovernance
2 Harrison Street, San Francisco, CA

[Wharton Cryptogovernance Workshop 7-19.docx](https://github.com/xaur/decred-news/files/3264565/Wharton.Cryptogovernance.Workshop.7-19.docx)

**Comment by xaur** [comment]
@nottrunner thanks, interesting text in that docx. Is it hosted as a page anywhere, e.g. meetup.com?

**Comment by nottrunner** [comment]
As a matter of fact yes.  Had no reason to look for it till you mentioned it.

Here is a link to the event announcement:
http://bit.ly/WhartonGCW

And a link to their event document from the site: 
http://bit.ly/WhartonCGWSummary

**Comment by xaur** [comment]
Thanks for the link. Added the event: https://github.com/xaur/decred-news/blob/draft05/journal/201905.md#events

Closing, reopen if anything needs correction or ping @bee in chats.

**Comment by nottrunner** [comment]
All good.
