### ISSUE TITLE
June Journal DC and VA events summary

### ISSUE THREAD

**Issue by nottrunner** [xaur/decred-news#85]
**Jun 12 Washington DC meetup**

The event had about 11 people in total in attendance.  Akin Sawyerr gave an overview presentation on Decred and answered questions from the audience.  The event was co-hosted by TechSpace Balston and the Dartmouth Entrepreneurial Network of DC.  A lot of questions were asked about our governance process, how we pay and manage contractors, and how Decred differed from platforms like Ethereum from a participation/contribution perspective.   

**Jun 19 Reston Golang meetup**

The event had 21 people in attendance, mostly developers.  Akin Sawyerr gave an overview presentation on Decred and answered questions from the audience.  The event was hosted by Comcast.
Most of the questions were of a general nature around how to acquire cryptocurrencies,  understanding the basic terminology, and the potential economic impact of cryptocurrencies.  Post the event a participant asked to know more about what Decred has built leveraging Golang, there is a desire to see actual code demos etc.

**Comment by xaur** [comment]
Nice and informative, thanks!

Included in the June draft https://github.com/xaur/decred-news/blob/draft06/journal/201906.md
